---
name: "Playback Reporting"
guid: "5c534381-91a3-43cb-907a-35aa02eb9d2c"
version: "10.0.0.0"
targetAbi: "10.7.0.0"
framework: net5.0
owner: "jellyfin"
overview: "Collect and show user play statistics"
description: "Collect and show user play statistics"
category: "General"
artifacts:
- "Jellyfin.Plugin.PlaybackReporting.dll"
changelog: >
  * Fix query to PlayActivity endpoint on User Playback Report (#35) @Stampede10343
  * Feature/client timezone awareness (#37) @Stampede10343
